# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# This pipeline will be extended to the OneESPT template

trigger:
- master
- releases/*

resources:
  repositories:
  - repository: AzureDevOps
    type: git
    name: AzureDevOps/AzureDevOps

  - repository: ConfigChange
    type: git
    name: AzureDevOps/AzureDevOps.ConfigChange

  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
- name: build_single_task
  displayName: Build Single Task
  type: boolean
  default: false
- name: task_name
  displayName: Task Name (List of tasks to build (e.g. BashV3 [, AzureCLIV1]))
  type: string
  default: TaskNameVN
- name: push_to_feed
  displayName: Push to Feed
  type: boolean
  default: false
- name: generate_prs
  displayName: Create hotfix PRs and Release
  type: boolean
  default: false
- name: deploy_all_tasks
  displayName: Build all tasks for deployment
  type: boolean
  default: false
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  currentDate: $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  taskName: ${{ parameters.task_name }}
  taskNameIsSet: ${{ not(eq(parameters.task_name, 'TaskNameVN')) }}
  isHotfix: ${{ and(eq(parameters.push_to_feed, true), eq(variables.taskNameIsSet, true)) }}
  runCodeQl: ${{ eq(parameters.enableCodeQL, true) }}

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      skipBuildTagsForGitHubPullRequests: true
    featureFlags:
      autoBaseline: false
    sdl:
      sbom:
        enabled: false
      baseline:
        baselineSet: default
        baselineFile: $(Build.SourcesDirectory)/.gdn/.gdnbaselines
      sourceAnalysisPool:
        name: 1ES-ABTT-Shared-Pool
        image: abtt-windows-2022
        os: windows
      sourceRepositoriesToScan: 
        exclude: 
          - repository: AzureDevOps
          - repository: ConfigChange
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: main
      jobs:

      - ${{ if parameters.build_single_task }}:

        - template: /ci/build-single-jobs.yml@self
          parameters:
            task_name: ${{ parameters.task_name }}
            push_to_feed: ${{ parameters.push_to_feed }}
            generate_prs: ${{ parameters.generate_prs }}

     