parameters:
- name: task_name
  type: string
- name: push_to_feed
  type: boolean
- name: generate_prs
  type: boolean

jobs:
# Build Single Task and stage hotfix
- job: build_single_task
  displayName: Build hotfix
  pool: 
    name: 1ES-ABTT-Shared-Pool
    image: abtt-windows-2022
    os: windows
  templateContext:
    outputs:
    # - output: buildArtifacts
    #   displayName: 'Publish hotfix artifact'
    #   PathtoPublish: hotfix-layout
    #   ArtifactName: hotfix
    # - ${{ if parameters.push_to_feed }}:
      # - output: buildArtifacts
      #   displayName: 'Publish per task NuGet package artifact'
      #   PathtoPublish: nuget-packages
      #   ArtifactName: IndividualNuGetPackages

    - output: nuget
      packagesToPush:  '$(Build.SourcesDirectory)/ConsoleApp.nupkg'
      packageParentPath: '$(Build.SourcesDirectory)'
      publishVstsFeed: 'c86767d8-af79-4303-a7e6-21da0ba435e2/e10d0795-57cd-4d7f-904e-5f39703cb096'
      nuGetFeedType: internal
      displayName: Push Nuget package
      # allowPackageConflicts: true # Optional. NuGetCommand task only.