schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - master
  always: true

trigger: none
pr: none

jobs:
- job: set_tasks
  displayName: Set tasks to test
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: |
      echo "##vso[task.setvariable variable=TASKS;isoutput=true]$(node ./ci/ci-test-tasks/get-tasks.js)"
    displayName: Set tasks to test
    name: set

- job: run_main_test_pipeline
  displayName: Run main test pipeline
  dependsOn: set_tasks
  timeoutInMinutes: 360
  variables:
  - name: tasks
    value: $[dependencies.set_tasks.outputs['set.TASKS']]
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: |
      npm i axios
    displayName: npm i axios
  - script: |
      echo $(tasks)
      node ./ci/ci-test-tasks/run-main-and-verify.js $(ADOToken) $(ADOUrl) $(System.TeamProject) $(MainPipelineId) $(tasks)
    displayName: Run test pipelines and verify results
    failOnStderr: true
